<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Макраб СК</title>
	<!-- Webix Library -->
	<script type="text/javascript" src="/webix/webix.min.js?{VERSION}"></script>
	<link rel="stylesheet" type="text/css" href="/webix/webix.min.css?{VERSION}">

    <!-- Chat -->
    <script type="text/javascript" src="/webix/libs/chat/chat.js"></script>
    <link rel="stylesheet" href="/webix/libs/chat/chat.css" type="text/css">
    <link rel="stylesheet" href="/webix/libs/chat/skins/material.css" type="text/css">

	<!-- Icons -->
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@mdi/font@6.9.96/css/materialdesignicons.min.css" crossorigin="anonymous">

    <!-- OneSignal -->
    <script src="https://cdn.onesignal.com/sdks/OneSignalSDK.js" async=""></script>
	
	<!-- App -->
	<script type="text/javascript" src="/codebase/app.js?{VERSION}"></script>
	<link rel="stylesheet" type="text/css" href="/codebase/app.css?{VERSION}">
	<script>
		webix.ready(function(){
			if (webix.env.touch)
				webix.ui.fullScreen();
			else if (webix.CustomScroll)
				webix.CustomScroll.init();
		
			const app = new AppMakrab({});
			app.render();
		});
	</script>

</head>
<body></body>
</html>